/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SharingRouteImport } from './routes/sharing'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as IndexRouteImport } from './routes/index'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingRoute = SharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/sharing': typeof SharingRoute
  '/tags': typeof TagsRoute
  '/trash': typeof TrashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/sharing': typeof SharingRoute
  '/tags': typeof TagsRoute
  '/trash': typeof TrashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/sharing': typeof SharingRoute
  '/tags': typeof TagsRoute
  '/trash': typeof TrashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/duplicates'
    | '/library'
    | '/projects'
    | '/search'
    | '/sharing'
    | '/tags'
    | '/trash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/duplicates'
    | '/library'
    | '/projects'
    | '/search'
    | '/sharing'
    | '/tags'
    | '/trash'
  id:
    | '__root__'
    | '/'
    | '/duplicates'
    | '/library'
    | '/projects'
    | '/search'
    | '/sharing'
    | '/tags'
    | '/trash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuplicatesRoute: typeof DuplicatesRoute
  LibraryRoute: typeof LibraryRoute
  ProjectsRoute: typeof ProjectsRoute
  SearchRoute: typeof SearchRoute
  SharingRoute: typeof SharingRoute
  TagsRoute: typeof TagsRoute
  TrashRoute: typeof TrashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuplicatesRoute: DuplicatesRoute,
  LibraryRoute: LibraryRoute,
  ProjectsRoute: ProjectsRoute,
  SearchRoute: SearchRoute,
  SharingRoute: SharingRoute,
  TagsRoute: TagsRoute,
  TrashRoute: TrashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
